services:
  nginx:
    image: nginx:alpine
    container_name: global-nginx
    user: "${UID}:${GID}"
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot:ro
      - /home/ubuntu/apps/oic/staticfiles:/srv/oic/staticfiles:ro
      - /home/ubuntu/apps/oic/media:/srv/oic/media:ro
      - /home/ubuntu/apps/kerenes-digital/staticfiles:/srv/kerenes/staticfiles:ro
      - /home/ubuntu/apps/kerenes-digital/media:/srv/kerenes/media:ro
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    networks:
      - webproxy

networks:
  webproxy:
    external: true